project:
  type: website

website:
  title: "WeatherWise SG"
  navbar:
    right:
      - text: "Proposal"
        href: "Proposal/Proposal.html"
      - text: "Discovery"
        menu: 
          - text: "Data Scraping"
            href: "WebScraping/Data_Scraping.html"
          - text: "Data Preparation"
            href: "WebScraping/Data_Preparation.html"
      - text: "Shiny App"
        menu: 
          - text: "User Guide"
            href: "PDF/WeatherWise SG User Guide.pdf"
          - text: "Shiny App"
            href: "https://shreyaagarwalrstudio.shinyapps.io/WeatherWiseSG/"
      - text: "Project Poster"
        href: "PDF/WeatherWise Poster.pdf"
      - text: "Team"
        href: "about.html"
        
format:
  html:
    theme:
      - minty
    css: styles.css
    toc: true
    number-sections: true

editor: visual

