project:
  type: website

website:
  title: "ISSS608-G6"
  navbar:
    right:
      - href: "Proposal/Proposal.html"
        text: "Proposal"
      - text: "Discovery"
      - text: "Shiny App"
      - text: "Poster"
      - href: "about.html"
        text: "Team"
format:
  html:
    theme:
      - minty
    css: styles.css
    toc: true

editor: visual

