---
title: "WeatherWise Singapore"
subtitle: "Visual Analytics For Unveiling Singapore's Evolving Climate"
---

# Motivation

Singapore’s tropical climate creates frequent and intense weather variations, which significantly impact sectors like urban planning, insurance, agriculture, and infrastructure. However, current weather platforms fall short in supporting data-driven decision-making due to:

-   **Basic Functionality**: Existing dashboards offer only real-time observations and short-term forecasts.

-   **No Advanced Analytics**: Lack of tools like trend forecasting, anomaly detection, and predictive modeling.

-   **Limited Historical Insights**: Inability to analyze long-term climate trends or generate custom comparisons.

These factors signify a need for a comprehensive platform offering statistical insights, spatial visualizations, and predictive modeling of Singapore weather measurements.

# Objectives

Our project tackles this challenge by offering a platform with rich analytics, interactive visualizations, and predictive tools tailored to Singapore’s context. This empowers businesses, researchers, and policymakers to make timely, strategic, and informed decisions, contributing to national climate resilience and smarter urban development.The project focuses on three main objectives:

1.  **Build a Comprehensive Weather Analytics Platform:** Integrate historical weather data from the Meteorological Service Singapore; covering temperature, rainfall, and wind, organized by station and time for easy access and analysis.

2.  **Develop Advanced Visual Analytics:** Offer interactive time series and geospatial visualizations—such as trend lines, heat maps, forecasting, and spatial interpolation - using robust statistical techniques to uncover patterns, anomalies, and future conditions in Singapore’s weather.

3.  **Ensure Independent and Flexible Use Across Sectors:** Design a user-friendly platform that supports diverse stakeholders - businesses, academics, and government agencies - with decision-making and strategic planning based on their unique needs.

# Main Features

The final **WeatherWise SG** Shiny Application consists of three core modules:

1.  **Time Series Data Analysis**: Exploratory and Confirmatory Data Analysis

    -   Exploratory and comparative data analysis to uncover trends in temperature, rainfall, and wind across regions and seasons.

    -   Visualization of seasonal/weather trends and inter-region comparisons.

    -   Statistical tests for station-wise comparison across different time intervals and parameters.

2.  **Time Series Forecasting**

    -   STL: Split data into trend, seasonal and residuals.

    -   ACF/PACF: Identify lags to set ARIMA/SARIMA p, q parameters.

    -   ADF Test: Check stationary and fine tune ARIMA/SARIMA (p,d,q)(P,D,Q).

    -   Benchmarking: Compare with other models – Prophet and ETS; evaluate different models using MAE, RMSE, MAPE.

3.  **Geospatial Analysis**

    -   Plot extreme weather events by station on Singapore map.

    -   Interpolate weather conditions at unmeasured locations based on nearby data points using Inverse Distance Weighted (IDW) and Kriging methods.
